In [215]:
import pandas as pd
import numpy as np
states_all_raw = pd.read_csv('data/states_all.csv')

In [216]:
df = states_all_raw.groupby('STATE').apply(
    lambda grp: grp.interpolate(method='linear', 
                                limit_direction='both', 
                                axis=0)).dropna().reset_index(drop=True)
display(df)

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,727716.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,121156.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,676297.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,311432.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_CALIFORNIA,CALIFORNIA,1992,5129788.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3591033.0,1578929.0,5254844.0,208.0,261.0,202.0,252.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2019_VIRGINIA,VIRGINIA,2019,1283493.0,16259274.0,1058146.0,6297587.0,8903541.0,16497520.0,8944614.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1679,2019_WASHINGTON,WASHINGTON,2019,1083973.0,14964364.0,1097684.0,9211201.0,4655479.0,15253296.0,7087365.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1680,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,276764.0,3391579.0,358068.0,1863062.0,1170449.0,3366566.0,1804235.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1681,2019_WISCONSIN,WISCONSIN,2019,857736.0,11697466.0,782610.0,5986763.0,4928093.0,11787535.0,5760418.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1682,2019_WYOMING,WYOMING,2019,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

# 1

In [217]:
from scipy.stats import zscore

df

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,727716.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,121156.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,676297.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,311432.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_CALIFORNIA,CALIFORNIA,1992,5129788.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3591033.0,1578929.0,5254844.0,208.0,261.0,202.0,252.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2019_VIRGINIA,VIRGINIA,2019,1283493.0,16259274.0,1058146.0,6297587.0,8903541.0,16497520.0,8944614.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1679,2019_WASHINGTON,WASHINGTON,2019,1083973.0,14964364.0,1097684.0,9211201.0,4655479.0,15253296.0,7087365.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1680,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,276764.0,3391579.0,358068.0,1863062.0,1170449.0,3366566.0,1804235.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1681,2019_WISCONSIN,WISCONSIN,2019,857736.0,11697466.0,782610.0,5986763.0,4928093.0,11787535.0,5760418.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1682,2019_WYOMING,WYOMING,2019,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

In [218]:
def outliercheck(df, thresh):
    z_rev = zscore(df['TOTAL_REVENUE'])
    z_exp = zscore(df['TOTAL_EXPENDITURE'])
    rev_outliers = np.where((z_rev < -thresh) | (z_rev > thresh))[0]
    exp_outliers = np.where((z_exp < -thresh) | (z_exp > thresh))[0]
    outliers = np.unique(np.append(rev_outliers,exp_outliers))
    return outliers, rev_outliers.size, exp_outliers.size, outliers.size
for i in range(1,7):
    print('threshold=',i,outliercheck(df, i)[1:])

threshold= 1 (176, 167, 179)
threshold= 2 (69, 73, 73)
threshold= 3 (55, 57, 57)
threshold= 4 (29, 30, 30)
threshold= 5 (10, 10, 10)
threshold= 6 (0, 0, 0)

There are outlier values for threshold values of |z| = 1, 2, 3, 4, and 5

# 2

In [219]:
df1 = df.drop(outliercheck(df,1)[0]).reset_index(drop=True)

In [220]:
df1

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,727716.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,121156.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,676297.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,311432.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_COLORADO,COLORADO,1992,539538.0,3185173.0,163253.0,1307986.0,1713934.0,3264826.0,1642466.0,...,50648.0,45025.0,34533.0,429624.0,192259.0,612635.0,221.0,272.0,217.0,264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499,2019_VIRGINIA,VIRGINIA,2019,1283493.0,16259274.0,1058146.0,6297587.0,8903541.0,16497520.0,8944614.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1500,2019_WASHINGTON,WASHINGTON,2019,1083973.0,14964364.0,1097684.0,9211201.0,4655479.0,15253296.0,7087365.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1501,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,276764.0,3391579.0,358068.0,1863062.0,1170449.0,3366566.0,1804235.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1502,2019_WISCONSIN,WISCONSIN,2019,857736.0,11697466.0,782610.0,5986763.0,4928093.0,11787535.0,5760418.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1503,2019_WYOMING,WYOMING,2019,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

# 3

In [221]:
dfdiff = df.copy()
dfdiff.insert(dfdiff.columns.get_loc('YEAR')+1, 'TOTAL_EXPENDITURE', dfdiff.pop('TOTAL_EXPENDITURE'))
dfdiff.insert(dfdiff.columns.get_loc('YEAR')+1, 'TOTAL_REVENUE', dfdiff.pop('TOTAL_REVENUE'))
dfdiff

,PRIMARY_KEY,STATE,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,2678885.0,2653798.0,727716.0,304177.0,1659028.0,715680.0,1481703.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,1049591.0,972488.0,121156.0,106780.0,720711.0,222100.0,498362.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,3258079.0,3401580.0,676297.0,297888.0,1369815.0,1590376.0,1435908.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,1711959.0,1743022.0,311432.0,178571.0,958785.0,574603.0,964323.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_CALIFORNIA,CALIFORNIA,1992,26260025.0,27138832.0,5129788.0,2072470.0,16546514.0,7641041.0,14358922.0,...,418418.0,363296.0,270675.0,3591033.0,1578929.0,5254844.0,208.0,261.0,202.0,252.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2019_VIRGINIA,VIRGINIA,2019,16259274.0,16497520.0,1283493.0,1058146.0,6297587.0,8903541.0,8944614.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1679,2019_WASHINGTON,WASHINGTON,2019,14964364.0,15253296.0,1083973.0,1097684.0,9211201.0,4655479.0,7087365.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1680,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,3391579.0,3366566.0,276764.0,358068.0,1863062.0,1170449.0,1804235.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1681,2019_WISCONSIN,WISCONSIN,2019,11697466.0,11787535.0,857736.0,782610.0,5986763.0,4928093.0,5760418.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1682,2019_WYOMING,WYOMING,2019,2044669.0,2034229.0,94511.0,123012.0,1175899.0,745758.0,921494.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

In [222]:
dfdiff.insert(dfdiff.columns.get_loc('TOTAL_EXPENDITURE')+1, 'BUDGET_DEFICIT', dfdiff['TOTAL_REVENUE']-dfdiff['TOTAL_EXPENDITURE'])
dfdiff

,PRIMARY_KEY,STATE,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,BUDGET_DEFICIT,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,2678885.0,2653798.0,25087.0,727716.0,304177.0,1659028.0,715680.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,1049591.0,972488.0,77103.0,121156.0,106780.0,720711.0,222100.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,3258079.0,3401580.0,-143501.0,676297.0,297888.0,1369815.0,1590376.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,1711959.0,1743022.0,-31063.0,311432.0,178571.0,958785.0,574603.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_CALIFORNIA,CALIFORNIA,1992,26260025.0,27138832.0,-878807.0,5129788.0,2072470.0,16546514.0,7641041.0,...,418418.0,363296.0,270675.0,3591033.0,1578929.0,5254844.0,208.0,261.0,202.0,252.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2019_VIRGINIA,VIRGINIA,2019,16259274.0,16497520.0,-238246.0,1283493.0,1058146.0,6297587.0,8903541.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1679,2019_WASHINGTON,WASHINGTON,2019,14964364.0,15253296.0,-288932.0,1083973.0,1097684.0,9211201.0,4655479.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1680,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,3391579.0,3366566.0,25013.0,276764.0,358068.0,1863062.0,1170449.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1681,2019_WISCONSIN,WISCONSIN,2019,11697466.0,11787535.0,-90069.0,857736.0,782610.0,5986763.0,4928093.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1682,2019_WYOMING,WYOMING,2019,2044669.0,2034229.0,10440.0,94511.0,123012.0,1175899.0,745758.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

In [223]:
def get_col_outliers(df, col, thresh):
    z = zscore(df[col])
    zoutliers = np.where((z < -thresh) | (z > thresh))[0]
    return zoutliers, zoutliers.size

In [225]:
for i in range(1,10):
    print(get_col_outliers(dfdiff, 'BUDGET_DEFICIT', i)[1])

201
88
36
22
18
15
2
1
0

There are outliers in the budget deficit for threshold values of |z| = 1, 2, ..., 8

In [226]:
dfdiff1 = dfdiff.drop(get_col_outliers(dfdiff, 'BUDGET_DEFICIT', 1)[0]).reset_index(drop=True)
dfdiff1

,PRIMARY_KEY,STATE,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,BUDGET_DEFICIT,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,2678885.0,2653798.0,25087.0,727716.0,304177.0,1659028.0,715680.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,1049591.0,972488.0,77103.0,121156.0,106780.0,720711.0,222100.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,3258079.0,3401580.0,-143501.0,676297.0,297888.0,1369815.0,1590376.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,1711959.0,1743022.0,-31063.0,311432.0,178571.0,958785.0,574603.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_COLORADO,COLORADO,1992,3185173.0,3264826.0,-79653.0,539538.0,163253.0,1307986.0,1713934.0,...,50648.0,45025.0,34533.0,429624.0,192259.0,612635.0,221.0,272.0,217.0,264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,2019_VIRGINIA,VIRGINIA,2019,16259274.0,16497520.0,-238246.0,1283493.0,1058146.0,6297587.0,8903541.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1478,2019_WASHINGTON,WASHINGTON,2019,14964364.0,15253296.0,-288932.0,1083973.0,1097684.0,9211201.0,4655479.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1479,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,3391579.0,3366566.0,25013.0,276764.0,358068.0,1863062.0,1170449.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1480,2019_WISCONSIN,WISCONSIN,2019,11697466.0,11787535.0,-90069.0,857736.0,782610.0,5986763.0,4928093.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1481,2019_WYOMING,WYOMING,2019,2044669.0,2034229.0,10440.0,94511.0,123012.0,1175899.0,745758.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

# 4

In [227]:
dfdiffalt = df1.copy()
dfdiffalt.insert(dfdiffalt.columns.get_loc('YEAR')+1, 'TOTAL_EXPENDITURE', dfdiffalt.pop('TOTAL_EXPENDITURE'))
dfdiffalt.insert(dfdiffalt.columns.get_loc('YEAR')+1, 'TOTAL_REVENUE', dfdiffalt.pop('TOTAL_REVENUE'))
dfdiffalt.insert(dfdiffalt.columns.get_loc('TOTAL_EXPENDITURE')+1, 'BUDGET_DEFICIT', dfdiffalt['TOTAL_REVENUE']-dfdiffalt['TOTAL_EXPENDITURE'])

In [228]:
for i in range(1,9):
    print(get_col_outliers(dfdiffalt, 'BUDGET_DEFICIT', i)[1])

256
77
39
20
4
2
2
0
0

There are outliers in the budget deficit for threshold values of |z| = 1, 2, ..., 7

In [229]:
dfdiffalt1 = dfdiffalt.drop(get_col_outliers(dfdiffalt, 'BUDGET_DEFICIT', 1)[0]).reset_index(drop=True)
dfdiffalt1

,PRIMARY_KEY,STATE,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,BUDGET_DEFICIT,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,2678885.0,2653798.0,25087.0,727716.0,304177.0,1659028.0,715680.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.0,252.0,207.0,255.0
1,1992_ALASKA,ALASKA,1992,1049591.0,972488.0,77103.0,121156.0,106780.0,720711.0,222100.0,...,9748.0,8789.0,6714.0,83217.0,36474.0,122487.0,233.0,279.0,212.0,256.0
2,1992_ARIZONA,ARIZONA,1992,3258079.0,3401580.0,-143501.0,676297.0,297888.0,1369815.0,1590376.0,...,55433.0,49081.0,37410.0,522450.0,217764.0,673477.0,215.0,265.0,209.0,260.0
3,1992_ARKANSAS,ARKANSAS,1992,1711959.0,1743022.0,-31063.0,311432.0,178571.0,958785.0,574603.0,...,34632.0,36011.0,27651.0,282911.0,133449.0,441490.0,210.0,256.0,211.0,256.0
4,1992_COLORADO,COLORADO,1992,3185173.0,3264826.0,-79653.0,539538.0,163253.0,1307986.0,1713934.0,...,50648.0,45025.0,34533.0,429624.0,192259.0,612635.0,221.0,272.0,217.0,264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,2019_VIRGINIA,VIRGINIA,2019,16259274.0,16497520.0,-238246.0,1283493.0,1058146.0,6297587.0,8903541.0,...,99305.0,96881.0,93121.0,773615.0,391435.0,1291462.0,247.0,287.0,224.0,262.0
1244,2019_WASHINGTON,WASHINGTON,2019,14964364.0,15253296.0,-288932.0,1083973.0,1097684.0,9211201.0,4655479.0,...,87366.0,81798.0,91892.0,667327.0,340375.0,1110367.0,240.0,286.0,220.0,266.0
1245,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,3391579.0,3366566.0,25013.0,276764.0,358068.0,1863062.0,1170449.0,...,20069.0,19958.0,18277.0,159595.0,78305.0,272266.0,231.0,272.0,213.0,256.0
1246,2019_WISCONSIN,WISCONSIN,2019,11697466.0,11787535.0,-90069.0,857736.0,782610.0,5986763.0,4928093.0,...,61913.0,62359.0,67026.0,488983.0,261916.0,860753.0,242.0,289.0,220.0,267.0
1247,2019_WYOMING,WYOMING,2019,2044669.0,2034229.0,10440.0,94511.0,123012.0,1175899.0,745758.0,...,7537.0,7086.0,6405.0,58998.0,27361.0,94258.0,246.0,286.0,227.0,265.0

# 5

In [230]:
dfdiff1.describe()

,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,BUDGET_DEFICIT,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
count,1482.000000,1.482000e+03,1.482000e+03,1482.000000,1.482000e+03,1.482000e+03,1.482000e+03,1.482000e+03,1.482000e+03,1.482000e+03,...,1482.000000,1482.000000,1482.000000,1.482000e+03,1.482000e+03,1.482000e+03,1482.000000,1482.000000,1482.000000,1482.000000
mean,2001.885965,7.229625e+06,7.247177e+06,-17551.975709,6.972407e+05,5.909334e+05,3.330307e+06,3.308385e+06,3.757812e+06,2.185340e+06,...,52935.684211,52169.064103,44812.206478,4.393413e+05,2.113867e+05,6.964232e+05,233.954124,276.383879,218.699899,263.571188
std,9.480059,7.707424e+06,7.700933e+06,204335.415162,6.737975e+05,6.594638e+05,3.303473e+06,4.040973e+06,4.026240e+06,2.323020e+06,...,51852.720712,50741.322850,43298.046425,4.304965e+05,2.050676e+05,6.803316e+05,10.142101,10.647644,7.798419,6.658713
min,1986.000000,4.656500e+05,4.816650e+05,-651081.000000,4.386600e+04,3.102000e+04,0.000000e+00,2.209300e+04,2.655490e+05,1.399630e+05,...,4577.000000,3371.000000,2572.000000,3.769800e+04,1.353000e+04,6.844900e+04,192.000000,231.000000,179.000000,236.000000
25%,1994.000000,2.180354e+06,2.100980e+06,-117287.250000,1.974242e+05,1.858030e+05,1.141334e+06,7.137785e+05,1.161386e+06,6.300840e+05,...,15605.000000,15506.500000,13857.250000,1.256310e+05,6.025575e+04,2.013942e+05,228.643939,270.000000,214.500000,259.281250
50%,2002.000000,4.688222e+06,4.645404e+06,-9179.500000,5.420875e+05,3.940600e+05,2.473098e+06,1.816272e+06,2.463190e+06,1.423276e+06,...,41806.000000,41094.500000,36256.000000,3.433310e+05,1.724095e+05,5.523495e+05,236.000000,278.500000,220.062500,265.000000
75%,2010.000000,9.156596e+06,9.187299e+06,69712.250000,8.961970e+05,7.808545e+05,4.262164e+06,3.971336e+06,4.702432e+06,2.800788e+06,...,68201.500000,67733.000000,62386.500000,5.672565e+05,2.793460e+05,8.984528e+05,241.500000,284.000000,224.000000,268.000000
max,2019.000000,7.824804e+07,7.836596e+07,557170.000000,6.226552e+06,7.556365e+06,4.236047e+07,2.833121e+07,3.895195e+07,2.350185e+07,...,493415.000000,500143.000000,496901.000000,3.929869e+06,1.949755e+06,6.413867e+06,253.000000,301.000000,237.000000,278.000000

In [231]:
dfdiffalt1.describe()

,YEAR,TOTAL_REVENUE,TOTAL_EXPENDITURE,BUDGET_DEFICIT,ENROLL,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
count,1248.000000,1.248000e+03,1.248000e+03,1248.000000,1.248000e+03,1.248000e+03,1.248000e+03,1.248000e+03,1.248000e+03,1.248000e+03,...,1248.000000,1248.000000,1248.000000,1.248000e+03,1.248000e+03,1.248000e+03,1248.000000,1248.000000,1248.00000,1248.000000
mean,2001.671474,5.200093e+06,5.219368e+06,-19274.862981,5.482247e+05,4.427330e+05,2.546909e+06,2.210451e+06,2.694469e+06,1.576188e+06,...,41877.028846,41217.003205,34848.165865,3.457184e+05,1.644423e+05,5.483781e+05,233.262617,275.950527,218.21855,263.265505
std,9.418426,4.296638e+06,4.304272e+06,131488.249503,4.465562e+05,3.663021e+05,2.017932e+06,2.160989e+06,2.236670e+06,1.321908e+06,...,34260.272977,33595.961917,27069.818602,2.854876e+05,1.323408e+05,4.460370e+05,10.340593,10.861399,7.83496,6.779573
min,1986.000000,4.656500e+05,4.816650e+05,-336681.000000,4.386600e+04,3.102000e+04,0.000000e+00,2.209300e+04,2.655490e+05,1.399630e+05,...,4577.000000,3371.000000,2572.000000,3.769800e+04,1.353000e+04,6.844900e+04,192.000000,231.000000,179.00000,236.000000
25%,1994.000000,1.957579e+06,1.963630e+06,-90069.000000,1.796820e+05,1.638035e+05,9.965555e+05,6.566090e+05,1.013209e+06,5.800405e+05,...,13456.000000,13012.000000,10986.500000,1.082070e+05,5.243150e+04,1.773705e+05,227.875000,269.372159,214.00000,259.000000
50%,2001.000000,3.790723e+06,3.818294e+06,-9507.500000,4.853525e+05,3.397990e+05,2.081087e+06,1.465249e+06,1.977888e+06,1.139754e+06,...,36038.500000,36124.500000,30502.000000,2.936870e+05,1.419500e+05,4.831360e+05,235.333333,278.250000,220.00000,265.000000
75%,2010.000000,7.418055e+06,7.501838e+06,41239.250000,8.025688e+05,6.431198e+05,3.654661e+06,2.942602e+06,3.826906e+06,2.242622e+06,...,60820.250000,58951.250000,49319.500000,4.891985e+05,2.376145e+05,7.957325e+05,241.000000,284.000000,223.50000,268.000000
max,2019.000000,2.302633e+07,2.302336e+07,326697.000000,3.740260e+06,2.598486e+06,1.117077e+07,1.369298e+07,1.157546e+07,7.524489e+06,...,294431.000000,290666.000000,195075.000000,2.407162e+06,1.059416e+06,3.828975e+06,253.000000,301.000000,237.00000,277.000000

The standard deviaion dropped significantly between the third and fourth questions. the median and means are largely the same.

# 6

The former seems most appropriate, because a high/low revenue year can cause a high/low expenditure year, so eliminating outlier revenues or expenditures (the latter method) eliminates years without outlier budget deficit values (it overcounts the outliers).